### ISSUE TITLE
Other microcontrollers?

### ISSUE THREAD

**Issue by terrag42** [jasoncoon/fastled-arcade#1]
Great looking project, it looks very fun to play with!
I would like to try building this project with a strip of 144 APA102s and an ESP8266. What was your thought process when choosing Teensy 3.2 for this project? I realize that the more capable chip in the Teensy is able to send accurately timed LED data and process the game code simultaneously. My thought is that APA102s do not need accurately timed LED data so perhaps a less expensive chip could be used?

**Comment by jasoncoon** [comment]
Thanks!

I went with the Teensy because I needed lots of inputs and outputs, and the Teensy 3.1/3.2 has internal [pullup resistors on all of the pins](https://www.pjrc.com/teensy/td_digital.html), which makes it easy.  I also didn't need wi-fi for anything, and wanted to keep it simple.  I needed two pins for each of the 5 buttons, one to read the switch, and another to control the LED.

I think there are enough pins on ESP8266 to pull it off, but I think you'll need external pullup/pulldown resistors.

**Comment by terrag42** [comment]
There are not enough pins on the ESP8266 to have 5 buttons with separate LEDs and a mode switch, but the pins all have pullup resistors built in. You could wire the LEDs to illuminate when pressed, but you'd lose some of the functionality of the "simon" game. I'll keep this option in mind for another project.
